# Generated by Django 5.1.7 on 2025-03-25 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apppark', '0001_initial'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.customuser'),
        ),
        migrations.AddField(
            model_name='floor',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apppark.parking'),
        ),
        migrations.AddField(
            model_name='slot',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apppark.floor'),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apppark.slot'),
        ),
    ]
